events {}

http {
    upstream rate_limiter_pool {  
        #Docker Compose's internal DNS will round-robin across all
        server rate-limiter-service:8001;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://rate_limiter_pool;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
    }
}